### ISSUE TITLE
Add Random Cropping and Overlapping images features

### ISSUE THREAD

**Issue by axiomcura** [WayScience/macrophage-striation-analysis#2]
@gwaybio has mentioned potential new features that may be important for analyzing macrophage striation from images. 

from #1 
> Maybe worth bringing up now, but probably not worth it holding up merging: Why do we need to walk over an image? Is it ok for two images to be overlapping? Why not randomly walk, which might prevent us from needing to hold everything in memory?

## Todo
- [ ] Develop a random crop walk 
- [ ] Allow cropping of overlapping images 
- [ ] create unit tests
